name: module3_task2
on:
  schedule:
    - cron: "0 2 * * *"
  push:
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Clone the Repo
        uses: actions/checkout@v3
      - working-directory: module3_task2
        run: ./setup.sh
      - working-directory: module3_task2
        run: make help
      - name: Build the server
        working-directory: module3_task2
        run: make build
      - name: Create a post
        working-directory: module3_task2
        run: make POST_NAME=welcome_again POST_TITLE="Welcome again" post
      - name: Use Package
        working-directory: module3_task2
        run: make package
      - name: Use lint
        working-directory: module3_task2
        run: make lint
      - name: Use unit-test
        working-directory: module3_task2
        run: make unit-tests
      - name: Use integration-tests
        working-directory: module3_task2
        run: make integration-tests
      - name: Use validate
        working-directory: module3_task2
        run: make validate
      - name: Save workflow
        uses: actions/upload-artifact@v3
        with:
          name: artifact-task2
          path: module3_task2/
